clojure-emacs/orchard

Makefile, project.clj
Like we did in clojure-emacs/cider-nrepl#501.
=> use lein-sysutils to clean up java version detection

src/orchard/apropos.clj
=> Fix typo in doc string

src/orchard/classpath.clj, src/orchard/info.clj, src/orchard/inspect.clj, src/orchard/java.clj, src/orchard/namespace.clj
- [ x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ x] The new code is not generating reflection warnings
Thanks!
=> Remove reflections

CHANGELOG.md, src/orchard/java.clj
Not adding tests since caching already hasn't been tested.
=> [java] Cache class-info for editable Java classes

CHANGELOG.md, src/orchard/clojuredocs.clj, src/orchard/meta.clj, test/orchard/clojuredocs_test.clj, test/orchard/meta_test.clj
=> Update to check internet connectivily for clojuredocs

src/orchard/inspect.clj, src/orchard/java.clj, src/orchard/java/legacy_parser.clj, src/orchard/java/resource.clj, src/orchard/namespace.clj
This reduces the number of reflection warnings shown when starting a
repl with *warn-on-reflection* true.
Thanks!
=> Remove some reflection warnings

src/orchard/cljs/meta.cljc, test/orchard/info_test.clj
=> info: handle scoped cljs macro

.circleci/config.yml, .clj-kondo/config.edn, .gitignore, Makefile, src/orchard/eldoc.clj, src/orchard/info.clj, src/orchard/inspect.clj, src/orchard/java.clj, src/orchard/java/classpath.clj, src/orchard/java/legacy_parser.clj, src/orchard/java/parser.clj, src/orchard/java/resource.clj, src/orchard/meta.clj, src/orchard/namespace.clj, src/orchard/xref.clj, test/orchard/apropos_test.clj, test/orchard/cljs/env_test.cljc, test/orchard/cljs/meta_test.cljc, test/orchard/eldoc_test.clj, test/orchard/info_test.clj, test/orchard/inspect_test.clj, test/orchard/java/classpath_test.clj, test/orchard/java_test.clj, test/orchard/meta_test.clj, test/orchard/misc_test.clj, test/orchard/namespace_test.clj, test/orchard/query_test.clj, test/orchard/spec_test.clj, test/orchard/xref_test.clj
=> Add clj-kondo

.circleci/config.yml, project.clj
Closes https://github.com/clojure-emacs/orchard/issues/88
Enabled by https://github.com/clojure-emacs/orchard/commit/70e42b52962572602c6bbbcfe1c7f547f2ab8a9e, https://github.com/clojure-emacs/orchard/commit/e30c2879e3fb367f58c1bc517a5ca957a3b18246 etc
=> CI: use `--illegal-access=deny` when possible

CHANGELOG.md, src/orchard/namespace.clj, test/orchard/namespace_test.clj
Fixes https://github.com/clojure-emacs/orchard/issues/142
=> Make read-namespace handle read conditionals gracefully

src/orchard/xref.clj, test/orchard/xref_test.clj
=> fixes AoT function lookup

.circleci/config.yml, .circleci/deploy/deploy_release.clj, CHANGELOG.md, Makefile, README.md, project.clj
Modelled after https://github.com/clojure-emacs/cider-nrepl/pull/745
=> Setup deployments in CI

.circleci/config.yml, CHANGELOG.md, src/orchard/inspect.clj, test-java/orchard/java/PrivateFieldClass.java, test/orchard/inspect_test.clj
Fixes an oversight made in https://github.com/clojure-emacs/orchard/pull/197
=> Inspector: restore private field access

CHANGELOG.md, src/orchard/java/classpath.clj, src/orchard/namespace.clj, test/orchard/namespace_test.clj
Fixes #222
Will confirm whether it's an actual improvement soon :)
=> Optimize the performance of namespace discovery

.circleci/config.yml, src/orchard/clojuredocs.clj, src/orchard/java/classpath.clj, test-newer-jdks/orchard/java/parser_test.clj, test/orchard/misc_test.clj
The goal is to make Orchard CI config match the configs of cider-nrepl (https://github.com/clojure-emacs/cider-nrepl/pull/841) and nREPL (https://github.com/nrepl/nrepl/pull/305).
=> [ci] Refactor CI wrt JDK8 and Clojure 1.9 compatibility

CHANGELOG.md, Makefile, README.md, src/orchard/inspect.clj, test/orchard/inspect_test.clj
This will fix a failing test in cider-nrepl.
=> `inspector/down`: return the usual value when called on nil `inspector` arguments

src/orchard/clojuredocs.clj, test/orchard/clojuredocs_test.clj
While profiling the test runs, I noticed that the function that parser Clojuredocs export spends significant time within `pmap` invocation. Looks like multiple threads are racing to compute the cache.
The change is unlikely to impact users anyhow, unless there is a situation with a slow machine like there was in Compliment and its own caching. In any case, this change wouldn't hurt.
=> [clojuredocs] Protect cache filling with a lock

CHANGELOG.md, java/mx/cider/orchard/TruncatingStringWriter.java, src/orchard/inspect.clj, src/orchard/print.clj, test/orchard/info_test.clj, test/orchard/inspect_test.clj, test/orchard/print_test.clj
=> [inspect] Extract inspect-value into a separate printer implementation

CHANGELOG.md, src/orchard/inspect.clj, test/orchard/inspect_test.clj
=> [inspector] Prettify printed members when inspecting a class object

.circleci/config.yml, project.clj
Copying question from Slack:
_I just noticed that Orchard test matrix separately runs tests with and without the :provided profile, can you please confirm that this still has a purpose and which one?_
=> Misc maintenance

CHANGELOG.md, src/orchard/inspect.clj, src/orchard/print.clj, test/orchard/inspect_test.clj, test/orchard/print_test.clj
Leaving this unmerged for now, let it just hang until we confirm that people are OK with the new non-spacious printing being the default.
=> [print] Remove support for spacious printing

CHANGELOG.md, src/orchard/inspect.clj, test/orchard/inspect_test.clj
> Closes https://github.com/clojure-emacs/orchard/issues/279
=> [inspect] Render metadata for atoms

test/orchard/java_test.clj
Since the merging of parsers, and removing the legacy one, some of the java-test code could be slightly simplified. I also merged two separate testcases that each parse ~80 classes into a single one to trim a few seconds from the test runtime.
=> [test] Simplify java-test namespace

CHANGELOG.md, Makefile, src/orchard/java.clj, src/orchard/java/source_files.clj
=> [java] Convert backslashes to forward slashes on Windows

CHANGELOG.md, src/orchard/trace.clj, test/orchard/trace_test.clj
=> [trace] Don't bind print-limiting vars when calling wrapped function

CHANGELOG.md, src/orchard/java/source_files.clj, test/orchard/java/source_files_test.clj
This addresses https://github.com/clojure-emacs/cider/issues/3775. These changes have been tested on Windows which comes as a separate PR.
=> [source-files] Properly convert file path to URI

CHANGELOG.md, src/orchard/inspect.clj, test/orchard/inspect_test.clj
=> [inspect] Display identity hashcode for objects

src/orchard/inspect.clj, test/orchard/inspect_test.clj
Technical change, users will not be impacted (except for faster serdes of rendered inspector content).
=> [inspect] Fuse consecutive strings in rendered data

src/orchard/inspect.clj, test/orchard/inspect_test.clj
This is just a small bit of fun and diversion.
---
=> [inspect] Custom messages for inspecting nil
