- src/orchard/java/parser.clj
Allows e.g. to have the following sample of tags for
java.util.ArrayList.java:
int MAX_ARRAY_SIZE
void grow (int minCapacity)
int hugeCapacity (int minCapacity)
int size ()
boolean isEmpty ()
boolean contains (Object o)
int indexOf (Object o)
int lastIndexOf (Object o)
Object clone ()
Object[] toArray ()
Object[] toArray (Object[] a)
> parser.clj (parse-info): Return :type for fields and methods

- .travis.yml
- Makefile
- project.clj
- test/orchard/namespace_test.clj
Pull request #4 noted that there were tests failing only under Java 9.  @bbatsov recalled an upstream issue related to classloader changes to support modules in Java 9 that was probably the root cause.
For now, this set of changes implements a test selector (as in, `lein with-profile +1.8 test :java9.0`) which allows individual tests to be labeled with metadata and excluded from java9 test passes.  Same mechanism will work for future (or past) versions of Java if needs arise.
While debugging this, I noticed Travis CI doesn't support `oraclejdk7` any longer. They dropped support after Oracle dropped support. So along with the test filtering I've also reverted to `openjdk7` since that's the only Java 7 compatible JVM available in Travis CI.  I also checked and they don't yet support an …
> Allow specific tests to be included/excluded based on JVM version

- src/orchard/classpath.clj
- src/orchard/namespace.clj
- test/orchard/classpath_test.clj
Per our discussion on clojure-emacs/cider-nrepl#486, we'll port the tool-independent portions of `cidernrepl.middleware.classpath` to Orchard.
> Port `cider.nrepl.middleware.classpath`

- test/orchard/classpath_test.clj
On Linux `(System/getProperty "java.io.tmpdir")` returns something like `/tmp`, without a trailing file separator. On OS X, it returns something like `/var/folders/rb/7tf4fbvs0f941dbsl1kwctbj1cz9rj/T/`, which does have a trailing slash.
We should therefore avoid string comparisons and compare `File`s.
> Fix `classpath-boot-test`

- .travis.yml
- Makefile
- README.md
- project.clj
This publish should achieve auto-publish to clojars for snapshots, and controlled publishes for releases too.
The changes are as follows.
(1) In `project.clj`, add a `:deploy-repositories` configuration for clojars.  Note that the clojars credentials do need to be set in the environment, but GPG signing is disabled because as of today there is no mechanism for unattended GPG signing in Leiningen (see https://github.com/technomancy/leiningen/pull/2279). Secure credentials set manually in the Travis CI "Settings" page will be elided from the build logs like this:
```
Setting environment variables from repository settings
$ export CLOJARS_USERNAME=[secure]
$ export CLOJARS_PASSWORD=[secure]
```
(2) In `project.clj` add a `:release-tasks` that performs manipulation of the project version …
> [Fix #9] auto publish snapshots to clojars

- .travis.yml
- Makefile
Two small changes that keep this repo in line with `cider-nrepl`
- the `after_success` script in the `cloverage` task needlessly checked the value of `$(TARGET)`
- `make deploy` would attempt (and fail) to deploy from a pull request job.  This does a more proper job of catching that.
> [#9] final cleanup to Travis CI config

- .travis.yml
- Makefile
Fixing two errors by updating the conditional test in the deploy
stage in `.travis.yml`
1. While `make release` creates a new version tag from which the
release should build and deploy, it turns out the resulting CI job
does not run the deploy task, because for those jobs the branch name
is not "master".  With this commit we allow deploys from branches
where the name matches "v#.#.#".
2. Anyone running Travis CI builds on their own fork of this project
ended up with failed deploy jobs because the Clojars credentials could
not be parsed. With this commit we exclude deploy jobs from even
running if we're on a fork.
> Ensure CI deploy jobs run at the proper times

- test/orchard/classloader_test.clj
- test/orchard/meta_test.clj
This is the companion to clojure-emacs/cider-nrepl#507 in which test namespaces were restructured to eliminate orchard dependencies. In a few cases, we needed to migrate tests into orchard.
> [clojure-emacs/cider-nrepl#489] Migrate tests from cider-nrepl

- src/orchard/meta.clj
- test/orchard/meta_test.clj
Per [this comment](https://github.com/clojure-emacs/cider-nrepl/pull/507#discussion_r168180244) in clojure-emacs/cider-nrepl#507 this particular function is not likely useful outside cider-nrepl. In order to clean up some implementation details on the other side, then, this change moves the function back.
This PR needs to be merged at the same time as clojure-emacs/cider-nrepl#507 to avoid breaking the builds.
> Migrate `relevant-meta` and `relevant-meta-keys` back to cider-nrepl

- .gitignore
- .travis.yml
- Makefile
- project.clj
The "make codox" target, together with the configuration in `project.clj` causes a set of documentation to be produced under `gh-pages/{branch}` for whatever is the current branch.
This is a step toward auto-doc generation in CI. However before we can automate there needs to be some admin work on the GitHub project.
----
> [#18] Add "make docs" target

- src/orchard/apropos.clj
- test/orchard/apropos_test.clj
`MultiFn`s are not `Fn`, but for the purpose of apropos they should be treated as such.
> Return apropos type of multifn as function

- src/orchard/misc.clj
- src/orchard/namespace.clj
- test/orchard/namespace_test.clj
When filtering the classpath with the project root lowercase both
sides of the comparison if the OS is Windows.
Enables running all tests on Windows, without this change no tests are
found because of a lower/upper case mismatch when filtering
the project neses on Windows.
Thanks!
> Make sure project namespaces are found on Windows* OSes

- eastwood.clj
- src/orchard/apropos.clj
- src/orchard/meta.clj
- src/orchard/namespace.clj
- src/orchard/query.clj
- test/orchard/apropos_test.clj
- test/orchard/namespace_test.clj
- test/orchard/query_test.clj
This was added to allow the sharing of query logic between various
different facets of cider.  Apropos, tests, and the namespace explorer
all expose different methods for operating on sets of vars from the
environment.
In particular, I want to do an apropos of only project namespaces, and
this isn't possible with current filtering rules.
I'm suspect that my naming is not very good, so feedback on that is good.  It's
also notable that this changes apropos to use clojure types natively, and
expects cider-nrepl to do the correct coercion from bencode.
> Add environment query functions

- src/orchard/eldoc.clj
The Clojure compiler is unable to devine that `partitioned` is a `clojure.lang.LazySeq`, and emits a reflection warning when Cider is run in a project where `*warn-on-reflection*` is set to `true` globally.
This type-hint removes that warning
- [ x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x ] All tests are passing
- [ x] The new code is not generating reflection warnings 
Thanks!
> Remove reflection warning

- src/orchard/java.clj
- test/orchard/java_test.clj
In recent version of cider-nrepl I've encountered an NPE when trying to load a file:
> #error { :cause nil
:via  [{:type java.lang.NullPointerException
:message nil
:at [clojure.lang.Symbol intern Symbol.java 59]}]
:trace
[[clojure.lang.Symbol intern Symbol.java 59]
[clojure.core$symbol invokeStatic core.clj 581]
[clojure.core$symbol invoke core.clj 576]
[cider.inlined_deps.orchard.v0v3v2.orchard.java$class_info_STAR_ invokeStatic java.clj 169]
[cider.inlined_deps.orchard.v0v3v2.orchard.java$class_info_STAR_ invoke java.clj 158]
[cider.inlined_deps.orchard.v0v3v2.orchard.java$class_info invokeStatic java.clj 201]
[cider.inlined_deps.orchard.v0v3v2.orchard.java$class_info invoke java.clj 195]
[cider.inlined_deps.orchard.v0v3v2.orchard.java$resolve_class invokeStatic java.clj 272] …
> get rid of npe in class-info*

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
A few useful goodies. Nothing too ground-breaking, so this might still have a chance to land into the upcoming cider-nrepl release.
- Render everything that implements j.u.List and j.u.Map as collections –– useful when interacting with Java libraries.
- Render inline arrays as collections – same.
- Truncate inline long strings and other objects – this helps when the inspected object has long strings as fields/contained values, or also unknown objects with toString implementations that produce long strings. The truncation limit is quite arbitrary, but I don't think this would be too useful to customize. Also, jumping into the string still renders it fully.
> Various inspector improvements

- src/orchard/classpath.clj
- test/orchard/classpath_test.clj
For the related issue see: https://github.com/clojure-emacs/cider/issues/2533.
I chose not to create an issue in orchard to keep the conversation in one place.
Let me know if there's any improvements that could be made concerning issues or the PR.
- [ X] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [ X] You've added tests to cover your change(s)
- [ X] All tests are passing
- [ X] The new code is not generating reflection warnings
> Turn all class paths to absolute paths on java9+ clojure-emacs#2533

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
- test/orchard/java_test.clj
Inspired by REBL, these are two features that would subsequently be available in CIDER inspector:
- `def` the currently inspected value as a var.
- prompt the user for an expression and eval it in the context where `v` is bound to the currently inspected value. Inspect the result just to be consistent.
> Add eval and def features to inspector

- src/orchard/java.clj
Fixes clojure-emacs/cider#2562. See https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.2 for a far more exhaustive discussion of what is actually going on during class loading/initialisation, and why we might need to guard against these errors when calling `Class/forName` – especially when native libraries are involved.
> Catch LinkageError when calling Class/forName

- src/orchard/spec.clj
- test/orchard/spec_test.clj
Added support for resolving namespace aliased keywords for the current namespace.
Changes:
- `spec-list` will return "::some-ns-alias/some-keyword" completions in addition to the fully qualified names for specs in namespaces that have an alias in the given ns.
- `spec-list` will return "::some-keyword" completions in addition to the fully qualified names for specs in the given ns.
- `spec-form` will expand both ns aliases before resolving the spec
- added tests for ns alias functionality
I will add a separate PR for CIDER to add `(cider-current-ns)` for `spec-list` and `spec-form` requests in `cider-client.el` if this is accepted.
> Namespace alias support for `spec-list` and `spec-form`

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
1. When inspecting objects that don't have special render handling, separate static and non-static fields. Also, sort fields by name. Looks like this:
2. Walk the class hierarchy to display not only immediate object's fields, but also fields inherited from superclasses.
> Raw object inspector improvements

- Makefile
- project.clj
- src/orchard/apropos.clj
- src/orchard/classpath.clj
- src/orchard/cljs/analysis.cljc
- src/orchard/cljs/meta.cljc
- src/orchard/info.clj
- src/orchard/meta.clj
- src/orchard/misc.clj
- test-resources/orchard/cljs/test_env.cljc
- test-resources/orchard/cljs/test_runner.cljs
- test-resources/orchard/test_macros.clj
- test-resources/orchard/test_ns.cljc
- test-resources/orchard/test_ns_dep.cljc
- test/orchard/cljs/env_test.cljc
- test/orchard/cljs/meta_test.cljc
- test/orchard/eldoc_test.clj
- test/orchard/info_test.clj
- test/orchard/misc_test.clj
In order to start consolidating Clojure and ClojureScript tooling under our apple orchard, this patch starts porting the info op from cljs-tooling. Consequently, it paves the way to port some of the orchard Clojure-only code to ClojureScript.
> Port cljs info and consolidate info api

- src/orchard/info.clj
- test-resources/orchard/test_ns.cljc
- test/orchard/info_test.clj
The info function was resolving aliases, using the unqualified name, before
resolving vars. This was a problem and it has been fixed with this patch.
> [Fix #53] Have info resolve vars before aliases

- src/orchard/classpath.clj
- src/orchard/info.clj
This patch brings a couple more boot hacks that were previously baked in the
cider-nrepl resource middleware into orchard. This enables the `info/file-info`
method to correctly resolve file resources.
> [Fix #52] Use boot-hack-classloader in file-info

- src/orchard/misc.clj
- test/orchard/misc_test.clj
According to [JEP223](http://openjdk.java.net/jeps/223), the minor version and security level parts of a Java version string must be omitted when both numbers are zero.
However, the current implementation of `orchard.misc/java-api-version` doesn't seem to take into account such a case. In fact, on my environment (OpenJDK 11) it fails to parse the version string and returns a wrong version:
```
$ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
```clojure
=> (System/getProperty "java.version")
"11"
=> (require '[orchard.misc :as misc])
nil
=> misc/java-api-version
7
```
This PR fixes the issue and makes `misc/java-api-version` return the correct version:
Oracle JDK 8:
```clojure
=> …
```
> Fix bug that fails to parse version string without minor version

- CHANGELOG.md
- src/orchard/namespace.clj
Apropos is broken right now and including inlined deps for this reason and another reason that will be patched on cider-nrepl and cider soon.
> Correct namespace prefix for inlined deps

- src/orchard/info.clj
- test/orchard/info_test.clj
There was a `NullPointerException` caused by an unnecessary call to
`cp/classpath-file-relative-path`. That code path is now avoided and as a bonus
the file key is not merged at all.
> [Fix #61] Avoid processing file info if there is no file entry

- src/orchard/info.clj
- src/orchard/java.clj
- src/orchard/resource.clj
- test/orchard/info_test.clj
- test/orchard/resource_test.clj
This patch brings in orchard the code necessary for resource resolution and
does a bit of refactoring: javadoc is now in `orchard.java`, where it belongs,
and a new `orchard.java.resource` namespace has been created containing the
actual reusable resource code.
> Move resource op from cider-nrepl and refactor

- src/orchard/meta.clj
- test/orchard/meta_test.clj
Wasn't threaded before so the value was computed and thrown away.
Thanks!
> Include specs in var-meta

- src/orchard/clojuredocs.clj
- test/orchard/clojuredocs_test.clj
Fix for https://github.com/clojure-emacs/orchard/pull/72#issuecomment-539140858
> Fix to skip checking internet connectivity for local files

- .gitignore
- src/orchard/cljs/meta.cljc
- src/orchard/info.clj
- src/orchard/meta.clj
- src/orchard/namespace.clj
- test-resources/orchard/cljs/test_canonical_source.cljs
- test-resources/orchard/test_no_defs.cljc
- test-resources/orchard/test_ns.cljc
- test/orchard/cljs/env_test.cljc
- test/orchard/info_test.clj
- test/orchard/meta_test.clj
- test/orchard/namespace_test.clj
Sending this PR in to get feedback.
The problem with `:file` entries being `nil` for namespaces where there are no `def`s is that `orchard.meta/ns-meta` relies on `clojure.core/ns-publics` to first pick out some of the `def`:ed vars in order to use `var-meta` on them.
In this PR I use a backup method for when `ns-publics` return an empty map.
However, in `orchard.info-test/file-resolution-no-defs-issue-75-test` I still get a `nil` back for the `:cljs` test. I have yet failed to figure that out. Any feedback on that is very welcome.
I'd also want some general feedback, as I am planning to try contribute to this library more, and I need to learn the best ways to do that. Cheers!
> [WIP] Fix bug with no `:file` for `info` on namespaces w/o defs

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Before this change, `nil` inside data structures did not render at all. The change does not require changes in cider-nrepl or cider (however, maybe tests would have to be updated when cider-nrepl bumps orchard version).
Before:
After:
> [inspector] Render nil as nil inside data structures

- CHANGELOG.md
- src/orchard/inspect.clj
On Java9+, when trying to inspect an object of a class that comes from the other module, and that object has private fields, JVM will throw InaccessibleObjectException when the inspector tries to set those private fields to accessible. Unfortunately, there doesn't seem a generic way to work around this, so at least we want the inspector to not crash in such situations.
Here's what the inspector shows after the patch:
> [inspector] Handle InaccessibleObjectException for foreign-module fields

- CHANGELOG.md
- src/orchard/misc.clj
- test/orchard/misc_test.clj
See comment here: https://github.com/clojure-emacs/orchard/pull/57#issuecomment-580518531
It's currently causing cider to fail for me when I jack in, and the traceback includes orchard failing to get the correct version string.
* Add a test for a java version string with a $OPT chunk
* Fix the test by lopping off the $OPT in the `let` clause of `parse-java-version`
I'm still pretty new to clojure, so if there's a more sane/elegant/appropriate way to lop off the $OPT bit, please let me know.
> Add handling for java version strings with $OPT chunks

- CHANGELOG.md
- src/orchard/misc.clj
- test/orchard/misc_test.clj
In a URLClassLoader not all URLs have to be files or directories.
Eg. Spring boot's fat jars add entries like "jar:file:..." to the
classpath
> Ignore non file URLs when checking for directory or file extensions

- CHANGELOG.md
- src/orchard/java.clj
- test/orchard/java_test.clj
the core-java-api url prefix used from clojure.java.javadoc includes
the java.base module so we just strip that out and use the module as
we had been doing
Thanks!
> Fix javadoc urls on java 11

- src/orchard/info.clj
- src/orchard/java.clj
- test-resources/orchard/test_ns.cljc
- test/orchard/info_test.clj
- test/orchard/java_test.clj
Here is the fix that seems to work. Please read the commit message, this is becoming black magic at this point and probably I will need to refactor stuff at some point.
I left the previous function name mostly untouched but given they return `info` candidates I really think that the `java/resolve-` prefix does not make too much sense. They probably belong to `orchard.info` but maybe this deserves another PR.
> Fix clj meta java symbol

- src/orchard/java/parser.clj
There's a file manager that backs each DocletEnvironment. As part of
parsing the docs, a jars from the classpath are loaded into it.  If you
do not close the file manager after you're done with the
DocletEnvironment, they're held onto forever.
Especially due to the `(future)` in orchard.java which parses the docs
for a bunch of classes, this can quickly snowball into the maximum file
limit being reached.  It won't fail in the foreground, but further
attempts to open files will fail.
Closing the file manager is recommended in
https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/tools/JavaCompiler.html
I attempted to reuse a file manager, but it didn't seem to work
correctly between invocations.  Presumably because of compiler state or
something.
> Fix large number of open files from java parser

- src/orchard/inspect.clj
- src/orchard/meta.clj
It removed all the remaining reflection warnings.
---
Thanks!
> Remove reflection warnings

- CHANGELOG.md
- README.md
- project.clj
- src/orchard/java.clj
- src/orchard/util/io.clj
- test/orchard/info_test.clj
* Default to silent class cache initialization
* Fixes clojure-emacs/refactor-nrepl#290
* Fix a flaky test ns
* See, for example: https://app.circleci.com/pipelines/github/clojure-emacs/orchard/267/workflows/4655c622-a1f7-4ab1-804c-d15e62641154/jobs/2329
> Default to silent class cache initialization

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
The limits after which the inspector truncates collection members are now
configurable. Previously they were hardcoded to 5 and 150 for collection and
atom (non-collection) members.
--------------------------------
Hi there!
I've been using cider-inspect to great effect recently. Occasionally, I run into cases where it would be really nice to see a collection like:
```
[[1 2 3 4 5 :some]
[1 2 3 4 5 :important]
[1 2 3 4 5 :thing]]
```
but it currently appears as:
```
Class: clojure.lang.PersistentVector
Contents: 
0. [ 1 2 3 4 5 ... ]
1. [ 1 2 3 4 5 ... ]
2. [ 1 2 3 4 5 ... ]
```
and I have to nav into each element one by one.
This change, and 2 more like it in cider-nrepl and cider, make the nested collection size limit configurable. While I was at it, I figured I might as well make the …
> [Inspector] Configure truncation limits

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Extends #111 to make maps truncate the same way as other collections, 
showing `*max-coll-size*` number of elements if they are too long.
----
Thanks!
> Truncate maps in inspector according to config

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/orchard/java.clj
- test/orchard/java/classpath_test.clj
- test/orchard/java/classpath_test/third_party_compat_test.clj
- test/orchard/java_test.clj
Fixes https://github.com/clojure-emacs/orchard/issues/113
Closes https://github.com/clojure-emacs/orchard/pull/112
The disabling is opt-in, i.e. nothing is changed (relative to current behavior) by default.
In order to exercise the proposed changes properly (and also, to prove that a plugin-based approach can work), it is proposed that the build matrix exercises both the dynapath and no-dynapath choices.
⚠️ Between and a tenative addition of JDK16 to the matrix, the matrix would become quite extensive - perhaps a bit over the top?
Green build in my account:
⚠️ for the no-dynapath choice _and_ JDK 8, a CI job will take 3m instead of 30-60s. Seems a legit issue, can investigate.
> Add ability to skip dynapath-based functionality

- .gitignore
- CHANGELOG.md
- project.clj
- src/orchard/misc.clj
- test/orchard/java/classpath_test.clj
I recently hit the corner case of a directory named `foo.jar` which caused orchard to choke on it.
This PR proposes a fix.
> `orchard.classpath`: don't fail on directories ending on .jar

- CHANGELOG.md
- src/orchard/namespace.clj
Parallelizes `orchard.namespace` when it makes sense (namely, IO-heavy ops) and it's safe to do so (i.e., no code loading performed).
This matters particularly in projects with numerous namespaces and large classpaths.
Makes https://github.com/clojure-emacs/cider-nrepl/pull/701 more efficient, particularly when `(namespace/project-namespaces)` will be invoked slightly more often (since a `def` became a `defn`).
> Parallelize `orchard.namespace`

- CHANGELOG.md
- src/orchard/info.clj
- test/orchard/info_test.clj
Currently when doing a `var-info` from a file before evaluating the `ns` form
always fails. The namespace object does not yet exist, and so none of the var
resolution strategies work.
However fully-qualified vars, namespace names, or built-ins (clojure.core
functions) could all be resolved, and it's frustrating that they aren't.
This adds a check to see if `(find-ns ns)` returns anything. If not then we are
initiating the lookup from a namespace that has not yet been defined, in which
case none of the lookup strategies will proceed, so we continue with doing the
lookup as if it had been initiated from `clojure.core`.
Thanks!
> Fix info lookups from namespaces that don't yet exist

- .circleci/config.yml
JDK16 can be removed after a few months as it's not LTS.
> Add JDK17 to the CI matrix

- CHANGELOG.md
- project.clj
- src/orchard/java/classpath.clj
- src/orchard/spec.clj
- test/orchard/java/classpath_test.clj
* Make `classpath-seq` handle non-existing files
* Fixes https://github.com/clojure-emacs/orchard/issues/125
* Upgrade linters
> Make `classpath-seq` handle non-existing files

- .circleci/config.yml
- project.clj
* Remove `repo` caching
* See https://github.com/clojure-emacs/cider-nrepl/commit/178556ebfeaf8719e197b7b6e128efe5f85f1a50#diff-f3e9d251e83fc546f51aa7cfc8ae605d64f20c232423c4b4eaf968f227b09ac6
* Cache the uncompressed JDK sources (see `project.clj`, JDK-8 only)
* CI: Use the JDK as part of the cache key
* Especially important for the `unzipped-jdk-source` stuff.
> CI improvements

- CHANGELOG.md
- project.clj
- src/orchard/apropos.clj
- test/orchard/apropos_test.clj
See https://github.com/clojure-emacs/orchard/issues/128
Tries fixing the bug itself, and also introduces a fallback. Will comment inline.
> Try fixing a bug in `apropos`

- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/orchard/info.clj
- test/orchard/info_test.clj
- test/orchard/java/resource_test.clj
* `info`: don't use a fallback for ns-qualified symbols
* Closes https://github.com/clojure-emacs/orchard/issues/133
* ℹ️ cider-nrepl will still need to get a couple tests adapted (and probably a couple more _added_)
* Add `make install` command
* Also includes our usual refinements (`-user` etc).
* Unflake a test
> `info`: don't use a fallback for ns-qualified symbols

- .clj-kondo/config.edn
- CHANGELOG.md
- Makefile
- dev/user.clj
- project.clj
- src-jdk8/orchard/java/legacy_parser.clj
- src-newer-jdks/orchard/java/parser.clj
- src/orchard/info.clj
- src/orchard/java.clj
- src/orchard/java/resource.clj
- src/orchard/misc.clj
- src/orchard/util/io.clj
- test-newer-jdks/orchard/java/parser_test.clj
- test/orchard/inspect_test.clj
- test/orchard/java/DummyClass.java
- test/orchard/java_test.clj
This PR replaces #124, see there for previous discussion. 
The java parser/legacy-parser returns a resource's `:file`, actually a relative
path as a string, and `:path`, the relative path converted to absolute. It does
this conversion through an `io/resource` lookup to find the file system location
of the artifact. There are two issues with this:
1. The return value of `io/resource` is discarded, even though it is needed
later on in `orchard.java`, causing unnecessary resource lookups.
2. The path is obtained through `(.getPath (io/resource path))`, which yields
nonsensical results when used on resources that are inside a JAR.
This change keeps the `:file` returned from java-parser (relative path string),
but removes the `:path` value in favor of a `:resource-url`, i.e. the return
value …
> Retain resource URL in java-parser results, improve caching

- CHANGELOG.md
- README.md
- project.clj
- src/orchard/xref.clj
- test/orchard/xref_test.clj
Fixes #51 
Uses Clojures internal class cache to also check anonymous function dependencies.
> fn-deps for lambdas

- src-jdk8/orchard/java/legacy_parser.clj
> Exclude orchard.java.legacy-parser from cljdoc

- CHANGELOG.md
- src/orchard/cljs/analysis.cljc
- test/orchard/cljs/analysis_test.clj
We got this error report https://gist.github.com/dgtized/aa046d06c921d4cb9f7dc51ea2729459 which can be reproduced by running cider-connect-cljs against https://github.com/dgtized/shimmers/tree/22f47d2d148ca7e52aa5a6e4f6e48b166c0abcd5.
> Fix a NPE in `cljs.analysis`

- doc/cljdoc.edn
Doesn't address #150 but should allow docs to build under cljdoc.
Thanks!
> Tell cljdoc to analyze API only under Clojure

- CHANGELOG.md
- src/orchard/namespace.clj
- test/orchard/namespace_test.clj
> Make orchard.namespace/classpath-namespaces resilient to faulty ns declarations

- CHANGELOG.md
- README.md
- doc/inspector.org
- src/orchard/inspect.clj
- src/orchard/misc.clj
- test/orchard/inspect_test.clj
- test/orchard/misc_test.clj
Hello,
this PR adds basic support for Datafy and Nav to Orchard's
Inspector. The PR adds a Datafy section to the inspection view.
A good introduction to Datafy and Nav can be found here:
<https://corfield.org/blog/2018/12/03/datafy-nav/>
Here's an overview how the UI looks like at the moment. In a nutshell,
a Datafy section is added to an object if it's datafy representation
is different than the original object.
This is done because datafy is defined on Object. Otherwise we would
show the same data in the datafy section as has been shown in a
previous section.
<a id="org0fc9983"></a>
(class (Object.))
Class: java.lang.Class
--- Interfaces:
--- Constructors:
public java.lang.Object()
--- Fields:
--- Methods:
public final native void java.lang.Object.wait(long) throws …
> Add Datafy and Nav support to the inspector

- CHANGELOG.md
- Makefile
- project.clj
- src/orchard/misc.clj
- src/orchard/spec.clj
- test/orchard/spec_test.clj
Hello,
this PR adds support for [spec-2](https://github.com/clojure/spec-alpha2) to orchard. spec-2 is supposed to be the successor of `clojure.spec.alpha`, but is still in an experimental state. The main advantage of spec-2 is that it adds `s/schema` and `s/select` which should improve some short comings of `s/keys` from the original spec. `s/schema` and `s/select` are supposed to help with re-using spec declarations. You would use `s/schema` to define the general shape of a data structure and then use `s/select` to make concrete sub selections of specs that have been defined with `s/schema`. It is not recommended to use spec-2 in production, but some people might do.
When Clojure Spec was initially released it lived under the namespace `clojure.spec`. Some time after the release it was …
> Add support for spec-2

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/misc.clj
- test/orchard/inspect_test.clj
This PR is a pre-requisite to work on https://github.com/clojure-emacs/cider/issues/3311
It adds a new function to the inspector to tap> the current value.
This function would needed to be called in a new operation in the cider-nrepl middleware.
> added function `tap-current-value` to inspector 

- src/orchard/eldoc.clj
- test/orchard/eldoc_test.clj
Fixes #165.
Currently, the eldoc args list for special forms includes the special form itself, which throws off the highlighting in Emacs' CIDER. This patch removes the special forms themselves from the args list. It specifically omits the Java interop special forms, because these, for some reason, do not include themselves in the :forms vector.
> Filter special form symbols from eldoc args list

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Because `Eduction` type implements `clojure.lang.Sequential` but not `clojure.lang.Counted`, the inspector threw an exception when trying to inspect it. A minor but annoying bug. Besides, there could be other similar classes out there, so it's worth fixing.
Thanks!
> [inspector] Fix exception thrown when inspecting short Eduction

- .circleci/deploy/deploy_release.clj
- .clj-kondo/config.edn
- CHANGELOG.md
- Makefile
- src-jdk8/orchard/java/legacy_parser.clj
- src-newer-jdks/orchard/java/parser.clj
- src/orchard/cljs/analysis.cljc
- src/orchard/cljs/meta.cljc
- src/orchard/clojuredocs.clj
- src/orchard/info.clj
- src/orchard/inspect.clj
- src/orchard/java.clj
- src/orchard/java/classpath.clj
- src/orchard/meta.clj
- src/orchard/misc.clj
- src/orchard/namespace.clj
- src/orchard/spec.clj
- src/orchard/util/os.clj
- src/orchard/xref.clj
- test-resources/orchard/test_ns.cljc
- test-resources/orchard/test_ns_dep.cljc
- test/orchard/apropos_test.clj
- test/orchard/info_test.clj
- test/orchard/inspect_test.clj
- test/orchard/java/classpath_test.clj
- test/orchard/meta_test.clj
- test/orchard/namespace_test.clj
- test/orchard/util/os_test.clj
Part of https://github.com/clojure-emacs/cider-nrepl/issues/788
Use case explained over there.
...I had attempted this before: https://github.com/clojure-emacs/cider-nrepl/pull/790 but it was targeting the wrong middleware. This impl is simpler / more predictable, needing no `pmap`-like parallelism.
I've tried this one locally, and it works as intended.
Works on CLJ and CLJS, tests added for both.
Cheers - V
> Infer var metadata for 'proxy' vars

- CHANGELOG.md
- src/orchard/xref.clj
Fixes https://github.com/clojure-emacs/orchard/issues/173
```clj
(time
(do
(doall (xref/fn-refs #'orchard.misc/as-sym))
1))
"Elapsed time: 3570.653465 msecs"
```
```clj
(time
(do
(doall (xref/fn-refs #'orchard.misc/as-sym))
1))
"Elapsed time: 528.020007 msecs"
```
`pmap` isn't exactly the best. I had a nice Claypoole integration in a discarded PR recently. Can be a global improvement after discussion later.
Cheers - V
> Parallelize `orchard.xref/fn-refs`

- CHANGELOG.md
- src/orchard/info.clj
- test/orchard/info_test.clj
> `info` cljs: don't mistakenly prioritize special form names over var names

- .gitignore
- Makefile
- README.md
- dev/user.clj
- project.clj
* Improve clj-kondo setup
* Prefer the official lein-clj-kondo plugin
* Use and cache the clj-kondo analysis
* Makefile: cache `spec2` directory
* Add a repl helper with enrich-classpath
* Follows https://github.com/clojure-emacs/enrich-classpath#any-lein-or-toolsdeps-project
* Paricularly needed for Orchard development.
Cheers - V
> Setup improvements

- .clj-kondo/config.edn
- CHANGELOG.md
- Makefile
- project.clj
- src-newer-jdks/orchard/java/parser.clj
- src-newer-jdks/orchard/java/parser_next.clj
- src-newer-jdks/orchard/java/parser_utils.clj
- src/orchard/java.clj
- test-newer-jdks/orchard/java/parser_next_test.clj
- test-newer-jdks/orchard/java/parser_test.clj
- test/orchard/java_test.clj
- test/orchard/test/util.clj
> Fixes https://github.com/clojure-emacs/orchard/issues/179
For Java stuff, we return `:doc` which is the parsed doc comments form the Java sources.
They're originally in a html-like markup language.
The existing approach parsed that html-like text with a HTML parser. Then, the HTML was converted to Markdown, which certainly does read more nicely.
However, that approach had a number of flaws:
* Newlines (not expressed as `<br>`, e.g. `\n`) were lost
* I find this flaw critical - without newlines, docstrings won't look nice in a UI
* e.g. eldoc trimming won't work properly.
* There's no workaround for this, since the HTML parser we were using eats newlines before we can do anything with them.
* Tables were not aligned, which hindered their readability
* non-html bits like `@code`, …
> Rework java `:doc`

- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src-newer-jdks/orchard/java/parser_next.clj
- test-java/orchard/java/DummyClass.java
- test-newer-jdks/orchard/java/parser_next_test.clj
- test-newer-jdks/orchard/java/parser_test.clj
* `:doc-block-tags-fragments`: exclude unhandled tags
* This helps keeping the rendered docstrings concise, and predictably formatted.
* Fixes https://github.com/clojure-emacs/orchard/issues/188
* 0.15.1
> `:doc-block-tags-fragments`: exclude unhandled tags

- .circleci/config.yml
- .gitignore
- Makefile
- project.clj
- src-jdk8/orchard/java/legacy_parser.clj
- src-newer-jdks/orchard/java/parser.clj
- src-newer-jdks/orchard/java/parser_next.clj
- src-newer-jdks/orchard/java/parser_utils.clj
- src/orchard/java.clj
- src/orchard/misc.clj
- test-newer-jdks/orchard/java/parser_next_test.clj
- test-newer-jdks/orchard/java/parser_test.clj
- test/orchard/info_test.clj
- test/orchard/inspect_test.clj
- test/orchard/java_test.clj
- test/orchard/test/util.clj
> Fixes https://github.com/clojure-emacs/orchard/issues/190
Performs some necessary preliminary fixes and then implements #190.
* Correctly consolidate arities info from two different sources (the Clojure Reflector, and .java source analysis) for a meaningful deep merge between then by computing `:non-generic-argtypes`
* Without arities that match 1:1 between the two sources, we cannot deep merge correctly: there will be duplicate entries (given the slightly different keys), which results in extra (and incorrect) entries shown to end users.
* This was a subtle bug in hidden in Orchard.
* Remove constructor info for now, given it's was incorrect and incomplete (and unused from cider.el) for both Reflector and Sources
* e.g. for a given constructor with 4 different signatures, maybe just 1 …
> Java source info: return `:formatted-arglists` when possible

- CHANGELOG.md
- src/orchard/indent.clj
- test/orchard/indent_test.clj
def-like macros should get no inference - these tend to be risky to make any assumption about.
I actually never particularly meant for def-like macros to be applied these rules of thumb - it was an oversight in implementation.
> Don't infer indentation for `def`-like macros

- Makefile
- src-jdk8/orchard/java/legacy_parser.clj
- src-newer-jdks/orchard/java/parser.clj
- src-newer-jdks/orchard/java/parser_next.clj
- src/orchard/java.clj
- test-newer-jdks/orchard/java/parser_next_test.clj
- test-newer-jdks/orchard/java/parser_test.clj
- test/orchard/java_test.clj
Restores all the constructor info that was temporarily disabled in https://github.com/clojure-emacs/orchard/pull/192, expanding related test coverage.
> Restore constuctor info

- CHANGELOG.md
- Makefile
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
> Part of https://github.com/clojure-emacs/cider/issues/3529
I can confirm these work as intended (as I already tried using them in cider / cider-nrepl)
Cheers - V
> `orchard.inspect`: offer new `previous-sibling` and `next-sibling` functions

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
* `orchard.inspect`: don't use `pr-str` over the main `Value: ` being inspected. 
* All values are already formatted as strings, so this `pr-str` was redundant.
* `orchard.inspect`: render non-accessible fields better.
* If a given field cannot be inspected (because it's private and the JDK module system prevents opening it), we return the fixed symbol `<non-inspectable value>` for representing its value, clients being free to elide its rendering.
* Now, for a given inspected Object (except Class objects), we return these sections, if present: `Instance fields`, `Static fields` ,`Private instance fields`, `Private static fields`.
* For Class objects, we keep grouping the fields under a single `Fields` section.
* `orchard.inspect`: render field names as symbols, not strings.
Cheers - V
> Inspector - misc

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
We already were trying this, but for maps, we were comparing `<x>` with `(datafy <x without nil-valued entries>)`, so the comparison was often different.
> `orchard.inspect`: don't render `Datafy` sections identical to the data they refer to

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
When inspecting a linear collection, the indices cause an ugly indentation shift on digit promotions (9->10, 99->100). This PR fixes this. Here's now it looks currently:
Here's how it looks after the patch:
In the future, we might want to do the similar for associative collections, but I think it's a more contentious topic. Some people don't like their values aligned to keys if it causes a large gap on the other side (me included). But aligning indices shouldn't be controversial since most of the time it's gonna be 1 space, 2 spaces at the very most in the edge case.
> [inspect] Right-align indices when rendering indexed collections

- CHANGELOG.md
- src/orchard/namespace.clj
- test/orchard/namespace_test.clj
Supports https://github.com/clojure-emacs/cider-nrepl/issues/830
The idea is to provide a means to easily get a list of `:import`ed classes, even if the underlying namespaces haven't been loaded yet.
Cheers - V
> Introduce new `read-ns-form`, `project-ns-forms`, `ns-form->imports` functions

- CHANGELOG.md
- project.clj
- src/orchard/java.clj
- test/orchard/java_test.clj
Haystack's Java needs are rather humble https://github.com/clojure-emacs/haystack/blob/3b0d8a464f60cb0c0e4114b9d853165d6d2f59ae/src/haystack/analyzer.clj#L91-L95 and we were responding slowly to those requests as we were parsing the underlying .java files when possible.
The introduced dyn var makes it possible for consumers to request less info, faster.
> `orchard.java`: add `*analyze-sources*` dynamic var

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
> Fixes https://github.com/clojure-emacs/orchard/issues/215
Named after `map-indexed` 😄
Cheers - V
> `orchard.inspect`: introduce `tap-indexed` function

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
> Closes https://github.com/clojure-emacs/orchard/issues/217
Adds a `Name` header to inspected Class objects.
Also makes some tests less fragile - they were breaking on JDK 21.
Cheers - V
> Add a `Name` header to inspected Class objects

- CHANGELOG.md
- src/orchard/java.clj
- src/orchard/meta.clj
This exception can be thrown on a case indifferent filesystem, eg. on
macOS.
One way this happens is if there is a java class with a camel cased name
that otherwise matches the name of a clojure namespace.
For some reason, when this exception was thrown, the classes in the
class cache were also getting initialised.
> Catch NoClassDefFoundError

- CHANGELOG.md
- src/orchard/xref.clj
- test/orchard/xref_test.clj
Performing `xref` over an invalid symbol (e.g. not a function) could result in an `eval` that would not return a `Class` object, which would then make the `.getDeclaredFields` call invalid.
> `orchard.xref`: avoid occasional null pointer access

- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/orchard/info.clj
- src/orchard/meta.clj
- test-resources/orchard/test_ns_dep.cljc
- test/orchard/info_test.clj
- test/orchard/inspect_test.clj
> Part of https://github.com/clojure-emacs/cider-nrepl/issues/851
It allows consumers to specify var metadata beyond Orchard's fixed whitelist.
Cheers - V
> `info*`, offer `:var-meta-allowlist` option

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Closes https://github.com/clojure-emacs/orchard/issues/216
- Makes `next-sibling`, `previous-sibling`, and `down` fns work well with pagination.
- `next-sibling` will continue to not go beyond the current page.
- Adds out-of-bound checks for `down`, `next-sibling`, `next-page`, and `previous-page` fns.
- Handle discrepancy with page-size and items-on-page when inspecting hash-maps.
> Fix inspector navigation fns to work with pagination

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Closes https://github.com/clojure-emacs/orchard/issues/232
I haven't faced any issues using `previous-sibling` across pages. Described the steps to reproduce in the issue.
This change allows `next-sibling` also to jump across pages.
> Allow `inspector/next-sibling` to go beyond the current page

- CHANGELOG.md
- Makefile
- README.md
- src/orchard/java.clj
See also: https://github.com/clojure-emacs/cider-nrepl/blob/d4bd53bc3145bf5627c44d336ce44eaad0fae55c/src/cider/nrepl.clj#L67-L69
Cheers - V
> `java/class-info`: handle `NoClassDefFoundError`s

- src-newer-jdks/orchard/java/parser.clj
- src-newer-jdks/orchard/java/parser_next.clj
- src/orchard/java.clj
I've noticed that most of the time spent during running tests is calling `source-info` from different places.
> [java] Improve Java parsing performance

- src/orchard/inspect.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
Nothing user-facing here except removing `eval-and-inspect`.
The controversial change of using vector for `:rendered` is in its own commit. No tests added because of Clojure's list/vector equality semantics.  Besides, `:rendered` still becomes a seq in the end for now, until this transformation is moved into cider-nrepl instead.
> [inspector] Misc improvements

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
I tried to make sense of all the ways to initiate a new inspection or re-inspection – `start`, `fresh`, `clear`. The problem with current state is that "an empty inspector" is not really a thing, it has to be inspecting something. So, an API call like `(fresh)` doesn't really make sense. Also, reusing an inspector to inspect a new object (unrelated to the current one) actually means only reusing the dynamically changed config (page size, truncation limits, etc.); we don't want to reuse any part of the state. 
The updated API has `start` as the single entrypoint into an inspector. 1-arg takes a value to be inspected and returns a rendered inspector object. 2-arg takes a value and the config. An already existing inspector object can be passed as the config. There are no other legal ways to …
> [inspector] Unify inspector entrypoints

- .circleci/config.yml
- CHANGELOG.md
- README.md
- doc/inspector.org
- project.clj
- src-newer-jdks/orchard/java/parser_utils.clj
- src/orchard/info.clj
- src/orchard/inspect.clj
- src/orchard/java.clj
- src/orchard/misc.clj
- src/orchard/xref.clj
- test/orchard/inspect_test.clj
- test/orchard/java_test.clj
- test/orchard/misc_test.clj
What do you say if we bite the bullet and drop 1.9? Short update on the reasons:
1. **1.9** has significant incompatibilities with JDK11+. That's why we only test 1.9 with JDK8 in Orchard and cider-nrepl.
2. **1.9** has been released in 2017. **1.10** has been released in 2018 (6 years ago).
3. Upgrade path **1.9->1.10** is trivial AFAIK. No controversial changes like in **1.8->1.9** (spec, error messages, single JAR split).
4. [State of Clojure 2023](surveymonkey.com/stories/SM-_2BH3b49f_2FXEkUlrb_2BJSThxg_3D_3D/) (1 year ago) had **1.9** usage at ~5%.
5. **1.12** is around the corner.
> Nuke support for Clojure 1.9

- src/orchard/misc.clj
- src/orchard/spec.clj
- test/orchard/inspect_test.clj
Some things that slipped past me in the 1.9 removal cleanup.
Also, remove handling of obscure `clojure.spec` namespace which only existed in some 1.9 alphas.
> More post-1.9 cleanup

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Path tracking is a big ball of hacks and assumptions. When the user goes down an item (= clicks on it in the UI), the path to the item is inferred from the positional idx of active items on the page. This assumption is broken (and there are bugs related to it) if there are other active elements on the page before the main collection items (e.g. rendered metadata values).
Sibling navigation relies on path tracking, so it is affected as well.
Sibling navigation uses inspector index (= rendered elements) to fetch prev/next element. This created problems if navigation goes beyond the current page, so `down` has been recently reworked to handle indices not rendered on the screen currently. This also introduced a bug that `down` works incorrectly if there are extra items rendered on the screen …
> [inspector] Rework inspector index, reimplement path tracking and sibling*, fix navigation with metadata

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Similarly to how it was already done for arrays, Counted objects now also show their size upfront.
> [inspector] Display count in the header for objects with known size

- test/orchard/inspect_test.clj
New representation of primitive arrays in 1.12 is `byte/1` and so on.
> Fix tests on Clojure 1.12.0-alpha10

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Pagination operations apply only to the primary object being inspected. You can't prev/next page large metadata or datafied representation. With datafied, you actually can, but only by luck – if the primary object is pageable, then the datafied representation will also page along. If metadata or datafied value are larger than page size, but the primary value is not, then you only get one page of meta and datafied and no way to jump to next page or full representation.
There are a few bugs around pagination where pressing Space on a non-paged object will raise an exception.
ARef inspection (atoms, for example) also reuses the paginated rendering but doesn't respond to prev/next page.
Rework pagination. Pagination data (whether object is pageable, whether it should be paged, chunk to be …
> [inspector] Rework pagination and datafy rendering

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Option was ignored when there was no default value for it in the map.
> [inspector] Allow customizing max-nested-depth

- java/mx/cider/orchard/TruncatingStringWriter.java
- src/orchard/inspect.clj
- test/orchard/print_test.clj
The bug is minor (in certain scenarios the printer can overflow the limit by <5%), so `0.24.0` is still good enough for cider-nrepl.
> [print] Prevent writer going over the total limit

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Currently, each config value has its own public setter with lots of repeatable code, room for error when copy-pasting, and spread documentation. Those setters are also not used when the inspector is started, so the validation does not work in that case.
This is me trying to wrangle this, to reduce the API surface, and to unify configuration between starting an inspector and changing the config in an existing one.
All existing functions are retained for compatibility and marked as deprecated.
> [inspector] Add `refresh` to replace individual set-* functions

- CHANGELOG.md
- src/orchard/inspect.clj
Misconfiguration throwing AssertionErrors makes them slip through cider-nrepl's `with-safe-transport`.
Overall, assertions are bad when integrating with other code.
> [inspector] Use preconditions that throw exceptions instead of errors

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
This is a feature that I've been wanting for a long long time. The idea is to have a toggle button (e.g. `v`) that forces inspector to render the current value as an unrecognized Java object – i.e., by displaying its fields.
This is very useful when working on Clojure itself or developing custom data structures that happen to implement List, Map, etc., but you want to see the implementation bits.
There are a couple of details I have not decided on yet:
1. Originally, I wanted this to be a toggle (normal mode <-> java mode). However, this has a potential to add more view modes. I'm not sure which ones those would be right away, but I can possibly imagine something like simple mode (don't show metadata and datafy – for cases where those are too large and distract from viewing the value), a …
> [inspector] Introduce object view mode

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
This PR has two implementations: a boring one and a fun one. Let's first decide which one to continue with, and then I'll take care of the tests.
1. The boring one simply adds the supersclass to the list of interfaces we currently show when inspecting the class. It will look like this (see APersistentVector):
Care is taken to sort only the interfaces (like we currently do) but the superclass will always stay on top.
2. The fun one prints the whole hierarchy all at once. Everything is clickable, of course. Like with the boring one, the superclass is always first, then come the interfaces. Duplicate interfaces are never shown twice, each is shown only the first time it comes up. Examples:
I like the fun one better because it gives much more information at a glance. You can discover with …
> [inspector] Show parent class hierarchy when inspecting a class

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
In the end, I decided to track `:view-mode` on the Orchard side and make it behave as a per-value remembered thing similar to how current-page is implemented (like I said in https://github.com/clojure-emacs/cider-nrepl/pull/880).
> [inspect] Re-implement :view-mode with a stack same as paging

- CHANGELOG.md
- java/mx/cider/orchard/TruncatingStringWriter.java
- src/orchard/print.clj
- test/orchard/print_test.clj
This is a fix for the issue raised on Slack: https://clojurians.slack.com/archives/C0617A8PQ/p1721356711913299
I've been blindly calling `.iterator` on any Clojure collection in the printer, but not everything that implements IPersistentVector or IPersistentSet is `Iterable`.
In another commit, I rewrite `TruncatingStringWriter`, which used by the printer, to throw an error when the limit is riched, in the same manner as nREPL's `QuotaBoundPrinter` works. This simplifies the implementation of `print-coll`.
> [print] Fix bug when a printed collection is not Iterable

- CHANGELOG.md
- project.clj
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
> [inspect] Don't crash when inspecting internal classes

- CHANGELOG.md
- src/orchard/trace.clj
- test/orchard/trace_test.clj
- test/orchard/trace_test/sample_ns.clj
Wanted to do this for a while. `clojure.tools.trace` has a bit ugly output for my taste and also adds a dependency for something simple enough that can live within Orchard. The API is compatible or almost compatible with `clojure.tools.trace`, so swapping one for another would be trivial.
My initial implementation of `orchard.trace` had pprint-like wrapping support and also configurable "spaciousness", but I decided to remove them for now for the sake of simplicity. This is something that could be added in the future if deemed necessary.
Output example:
```clj
(orchard.trace-test.sample-ns/fibo 5)
│ 
│ (orchard.trace-test.sample-ns/fibo 3)
│ │ 
│ │ (orchard.trace-test.sample-ns/fibo 1)
│ │ │ 
│ │ └─→ 1
│ │ 
│ │ (orchard.trace-test.sample-ns/fibo 2)
│ │ │ 
│ │ │ …
```
> [trace] Add orchard.trace

- CHANGELOG.md
- src/orchard/info.clj
- src/orchard/java/classpath.clj
- src/orchard/java/resource.clj
- src/orchard/misc.clj
- test/orchard/info_test.clj
This PR removes handling of Boot's classpath magic. This would not make CIDER "broken" with Boot, the REPL will still start and work (if somebody manages to run Boot, that is), but the "jump to source" functionality will become wobbly.
---
> Remove special handling of Boot

- CHANGELOG.md
- src/orchard/inspect.clj
Happens when the object declares but doesn't implement all the necessary methods. Such object is not correct, but we should still be aware.
> [inspect] Don't crash when field contains non-equiv()able value

- CHANGELOG.md
- project.clj
- src/orchard/java.clj
- src/orchard/java/legacy_parser.clj
- src/orchard/java/modules.clj
- src/orchard/java/parser.clj
- src/orchard/java/parser_utils.clj
Context here: https://clojurians.slack.com/archives/C17JYSA3H/p1724172844138059
On the JRE, loading CIDER (and hence Orchard) produces an exception like this:
```
error in process sentinel: Could not start nREPL server: Downloading: cider/cider-nrepl/0.45.0/cider-nrepl-0.45.0.pom from clojars
Downloading: cider/orchard/0.22.0/orchard-0.22.0.pom from clojars
Downloading: mx/cider/logjam/0.2.0/logjam-0.2.0.pom from clojars
Downloading: cider/orchard/0.22.0/orchard-0.22.0.jar from clojars
Downloading: mx/cider/logjam/0.2.0/logjam-0.2.0.jar from clojars
Downloading: cider/cider-nrepl/0.45.0/cider-nrepl-0.45.0.jar from clojars
Execution error (IllegalArgumentException) at orchard.misc/require-and-resolve (misc.clj:161).
No such namespace: orchard.java.parser-utils
```
---
> [java] Don't crash if none of the parsers can be initialized

- CHANGELOG.md
- Makefile
- project.clj
- src/orchard/java.clj
This allows parsers to correctly initialize even if JDK sources aren't present.
> [java] Parse LruMap.java as indicator of a working parser

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
HashMap size was not shown in the inspector because it's not an instance of `Counted`. This PR fixes that.
> [inspect] Show count for HashMap and other maps

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Addresses #268.
This influences both the `Count` indicator in the header for types like `Cons` or small lazy seqs, but also displays such collections as lists when they are inside containers like atoms, delays, etc.
> [inspect] Count small lazy collections

- .circleci/config.yml
- .clj-kondo/config.edn
- Makefile
- project.clj
- Update linter versions.
- Reduce the matrix for Eastwood.
- Merge back test matrices since we now only have one parser and we download sources for all JDK versions.
> [ci] Refactor linter and other CI config

- .gitignore
- CHANGELOG.md
- Makefile
- README.md
- project.clj
- src/orchard/info.clj
- src/orchard/java.clj
- src/orchard/java/modules.clj
- src/orchard/java/parser_next.clj
- src/orchard/java/source_files.clj
- test/orchard/info_test.clj
- test/orchard/java/parser_next_test.clj
- test/orchard/java/source_files_test.clj
- test/orchard/java_test.clj
- test/orchard/test/util.clj
This is the first step – and a big one – in redoing Orchard's interaction with Java sources. It's kinda difficult to split it into smaller chunks, so I'm going to explain the changes below.
1. The main idea is this – the user may have some downloaded Java sources on the disk. We used to look for those sources on classpath, but it's not obligatory. In fact, there is no reason to put the sources themselves on the classpath, we can read them of the disk just the same, just have to discover them.
2. The biggest obvious place where we can find Java sources is the Java home directory. We know where it is, we know how to find the source archive in it, thus we can parse sources and enable jump-to-definition for those without having them on the classpath.
3. Another possible source of sources …
> [java] Rework Java sources discovery

- CHANGELOG.md
- README.md
- src/orchard/java.clj
- src/orchard/java/source_files.clj
- test/orchard/java/source_files_test.clj
Finally, a way to download source JARs at runtime. Sister PRs: https://github.com/clojure-emacs/cider-nrepl/pull/911, https://github.com/clojure-emacs/cider/pull/3769.
I tried a few approaches and settled with this one – downloading happens within `class->source-file-url` if `*download-sources-jar-fn*` is bound. The caller is expected to bind it to something that eventually invokes `download-sources-jar-for-coordinates` but can do custom logic and predicates too. I'm not 100% happy with this solution, it feels kinda awkward, but this is the best I could do. I honestly tried to make it strictly "cider-nrepl invokes Orchard", but the amount of repeated work was too much. Common Lisp condition system would actually make this cleaner, but hey, that's what dynamic vars actually are in the end, …
> [java] Download 3rd-party Java sources from Maven

- CHANGELOG.md
- src/orchard/java.clj
- src/orchard/misc.clj
- test/orchard/java_test.clj
Context here: https://clojurians.slack.com/archives/CBE668G4R/p1735807627304719
Cider-nrepl's `info` doc says that `:file` key contains either an absolute URL or a relative path to the file – but still a filesystem path. The current class-info* implementation returns `:file` as a path on the classpath. Sometimes, it is a valid as a file path – if the class is local to the project, but more often the class is external, and the resource path doesn't work as the file path.
This PR fixes that.
---
> [java] Return actual paths as :file in class-info*

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/java/classpath.clj
- src/orchard/meta.clj
- src/orchard/namespace.clj
- test/orchard/inspect_test.clj
This PR removes most of the older deprecated functions. cider-nrepl no longer uses them, and I doubt anybody else does.
> Remove deprecated functions and refactor some tests

- CHANGELOG.md
- src/orchard/java.clj
- src/orchard/java/parser_next.clj
- src/orchard/misc.clj
- test/orchard/java/parser_next_test.clj
- test/orchard/misc_test.clj
Further cleanup of stuff we no longer need. Most of these were necessary when we supported pre-1.10, but they are not used anymore.
I don't fret making breaking changes here since I don't think that relying on a misc namespace of a 3rd-party library is such a good idea anyway.
> Remove unused orchard.misc functions

- src/orchard/java.clj
- src/orchard/java/parser_next.clj
- test/orchard/info_test.clj
Now that we have a single parser that can be loaded pretty reliably (we don't depend on --add-opens), we can avoid stuffing it in a delay. Besides, that delay is touched very early on in cider-nrepl anyway.
> [java] Don't delay loading parser-next namespace, move exception handling

- CHANGELOG.md
- src/orchard/info.clj
- src/orchard/java.clj
- src/orchard/java/parser_next.clj
- src/orchard/meta.clj
- test/orchard/info_test.clj
- test/orchard/java_test.clj
This is part 1 of simplifying Haystack usecases. I think this PR is self-sufficient enough to be reviewed individually.
The proposed changes relax the requirements for Java classes/members and Clojure vars to be inferred using `orchard.info/info`. Now it can recognize all printed stacktrace formats. The examples are in the tests. This influences:
- Better jump to definition (can jump directly from the REPL output without no extra prep)
- Better cider-doc support
- Even eldoc (this looks a bit funny, consider yourself if we should restrict this somehow).
---
> More permissive orchard.info parsing of stacktrace output

- .clj-kondo/config.edn
- src/orchard/cljs/analysis.cljc
- src/orchard/clojuredocs.clj
- src/orchard/indent.clj
- src/orchard/inspect.clj
- src/orchard/java.clj
- src/orchard/java/parser_next.clj
- src/orchard/java/source_files.clj
- src/orchard/meta.clj
- src/orchard/misc.clj
- src/orchard/namespace.clj
- src/orchard/spec.clj
- src/orchard/trace.clj
- src/orchard/util/os.clj
- src/orchard/xref.clj
- test-resources/orchard/test_ns.cljc
- test-resources/orchard/test_ns_dep.cljc
- test/orchard/apropos_test.clj
- test/orchard/clojuredocs_test.clj
- test/orchard/info_test.clj
- test/orchard/inspect_test.clj
- test/orchard/java/classpath_test.clj
- test/orchard/java/parser_next_test.clj
- test/orchard/java/resource_test.clj
- test/orchard/java_test.clj
- test/orchard/namespace_test.clj
- test/orchard/test/util.clj
- test/orchard/util/os_test.clj
I know this may look petty, but I lost count how many times I've typed `(str/`, pressed complete, figured that the namespace probably doesn't have clojure.string required yet, going to the ns form only to discover it's `string` in this project. I'm not a fan of useless churn, but this is seriously annoying. Let's agree that `str/` is an "industry standard" and forget about this.
> Revert clojure.string alias back to str

- CHANGELOG.md
- src/orchard/stacktrace.clj
- test/orchard/stacktrace_test.clj
This PR brings `haystack.analyzer` back home to Orchard. This is not an exact copy; I also did a lot of work in rewriting it to make leaner and faster.
- Pre-1.10 support bits are removed.
- Complete rework of :project flag for frames. Previously, it was implemented by scanning the classpath for all loaded namespaces, and comparing frame's namespace against that set. Now, frame namespace tries to be resolved to classpath resource. If successful, and the path starts with project's workdir, the frame is considered :project. Ridiculously faster this way (< 1 ms vs ~100 ms in a big project).
- Many functions were refactored without changing the behavior. 
- Test namespace was ported almost without behavior changes (but was rewritten to matcher-combinators).
The next step will be to switch …
> [stacktrace] Repatriate stacktrace analyzer from Haystack

- src/orchard/stacktrace.clj
- test/orchard/stacktrace_test.clj
I found this confusing while I was redoing the the exception handling subsystem. This flag gives an impression that such exceptions (with "compile-like" being true) are handled differently by CIDER, e.g. they don't pop up cider-error buffer and only displayed inline with overlays. That's not true – this flag is not used anywhere in CIDER, cider-nrepl, or Calva. And I don't think it is a good idea to do that either – reflection errors are not compile-time errors and it's misleading to present them so.
To avoid the confusion, I propose to remove this unused flag. Changelog update does not feel necessary since `orchard.stacktrace` is still new.
> [stacktrace] Stop sending compile-like flag

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
- test/orchard/print_test.clj
Two things here.
I've replaced the default printer for throwables that is used by the inspector (when a value is rendered inline) and the debugger to a custom one. The default printer used `print-method` implementation for throwables which in turn uses `print-throwable` – the default data-like representation of throwables. See below:
The multi-line pseudo pretty-printing that `print-throwable` performs here really doesn't vibe with the inline display nature of inspector and debugger. In the inspector, the multi-line value makes it harder to find the next value in the map/list. in the debugger, you might argue that seeing those few stackframes (before they are truncated) is useful, but it looks messy nonetheless. So, here's the new inlined rendering for throwables:
It still spans multiple …
> [inspector] Inspectable exceptions

- CHANGELOG.md
- src/orchard/misc.clj
- src/orchard/stacktrace.clj
- test/orchard/stacktrace_test.clj
To accommodate for changes I'm making in https://github.com/clojure-emacs/cider/pull/3789, we need the triaged compiler exception string to be available within the analyzed exception itself, not just the stderr output. The solution is clunky, and I would do it differently if we didn't already have this cruft of sending one message per cause, but it's cheaper from the compatibility perspective to add it here.
The second commit is a minor addition. The new pmap in orchard.misc is more efficient and doesn't yank the Futures pool.
---
> [stacktrace] Add ex-str-formatted message to analyzed causes

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/inspect/analytics.clj
- test/orchard/inspect/analytics_test.clj
- test/orchard/inspect_test.clj
Now this is a feature I had on my mind for quite some time, and one I'm very excited about. The idea is to have all kinds of analytics that the inspector can automatically (on demand) compute when the user inspects a large collection of data. It happens very often to me that I inspect something big and can't really grasp some characteristics of that data just by looking at it visually at the inspector, and I start running all the things on it like `frequencies`, `(map type coll)`, etc. Having the inspector do it without leaving the inspector window is crazily convenient.
Bonus: we can present the analytics data **using the inspector itself**. I'm almost crying as I'm writing this. It is a thing of beauty; Father McCarthy smiles upon us from heaven.
Some screenshots how it would look like …
> [inspect] Introduce analytics

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Another big feature for the inspector that has been requested before and will make some people's lives better.
We already have the concept of a "view mode" that currently switches between :normal and :object (force-showing Java object fields instead of custom rendering).
A new view-mode called `:table` can also be cycled through using the same `v` keybinding. 
- Table view mode works for sequences of maps or tuples.
- Supports paging.
- All elements inside the table are clickable/navigable!
- There are some minor lackings, like path is not recorded if you navigate through the table, but it can be fixed later.
Here's how the end result looks:
---
> [inspect] Add :table view-mode

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
I've started using the pretty inspector view and I'm willing to change a couple of things:
- Make the threshold for long key wrap larger. Let's start with 50, this should reduce spurious line-wraps.
- Allocate 80 characters of width to the printer regardless of indentation. Currently, if the map key is long, this squeezes the available space for the pretty-printed a lot, making it very thin and unreadable.
- Show `:pretty` in View mode section when it's enabled.
- Don't pretty print `Value:` in object mode (or in normal mode for unknown objects) to keep this a single line. 
What do you think, @r0man?
---
> [inspect] Tune pretty-printing

- CHANGELOG.md
- src/orchard/print.clj
- test/orchard/inspect_test.clj
- test/orchard/print_test.clj
I want to make the custom printing we do in inspector, debugger, and the customly inject print-methods in cider-nrepl more consistent with each other. This PR adds print handling for futures, promises, namespaces, multimethods (things that cider-nrepl already performs prettyfication of), downcases the custom printed representation names (again, like cider-nrepl does), and other minor things.
---
> [print] Make orchard.print more consistent with CIDER printing

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/pp.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
- test/orchard/pp_test.clj
- test/orchard/print_test.clj
This achieves better displayed consistency between orchard.print and orchard.pp. It also cuts down some code from orchard.pp that's already implemented in orchard.print.
---
> [pp] Reuse orchard.print in orchard.pp

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/inspect/analytics.clj
- test/orchard/inspect_test.clj
First part is pretty minor – allow analytics for all maps and for arrays.
~The second part is a bit more involved. Sometimes, it is beneficial to display a map as map after you order it somehow – sort by keys or values or anyhow else. However, turning that sorted list of MapEntries back into an array-map just so that inspector or printer displays it properly without messing up the entry order is inefficient. Thus, I've added a meta flag that is interpreted by inspector, printer, and pretty-printer as "show this sequence of mapentries as a map".~
~This is currently only used for displaying frequencies computed by inspector analytics. We have tests for that functionality, so no new tests are necessary.~
---
> Inspector analytics improvements

- .circleci/config.yml
We currently only test with JDK8 and 24, and with 8 being soft-deprecated anyway, it makes sense to just treat Eastwood as all other linters.
> [ci] Run Eastwood together with other linters

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
Because there are more view modes now, and they all work conditionally, and also to facilitate discovery, I've reworked how they are displayed and changed. Orchard now has its own "toggle view mode" functionality (previously it was in cider-nrepl).
All view modes that are available for the currently inspected objects are displayed, and the enabled one is marked with a special symbol.
---
> [inspect] Rework view-mode toggling

- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
More inspector refactoring with no significant user-facing component but unifies some things and improves performance (useful when e.g. flipping rapidly through a paginated collection).
> [inspect] Performance refactoring

- CHANGELOG.md
- src/orchard/inspect.clj
- test/orchard/inspect_test.clj
> [inspect] Misc features

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/pp.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
As was discussed on Slack.
The current final version looks like this:
---
> [inspect] Add diff mode

- .circleci/config.yml
- .circleci/download-jdk-sources.sh
- CHANGELOG.md
- src/orchard/java/compatibility.clj
- src/orchard/java/source_files.clj
- test/orchard/java/source_files_test.clj
Turns out I had wrong heuristic for figuring out if a class is a JDK one.
---
> [src-files] Correctly resolve source files for non-base JDK classes

- CHANGELOG.md
- src/orchard/inspect.clj
- src/orchard/print.clj
- test/orchard/inspect_test.clj
- test/orchard/print_test.clj
This is an idea to address https://github.com/clojure-emacs/cider/issues/3841. I think most of the time when people use long qualified keywords, it happens when using shortened syntax `::foo` or `::alias/foo`. The proposed feature tries to reconstruct the shortened syntax by providing a config paramter `:pov-ns` (Point-of-View namespace) from where the inspection is initiated. Example, inspecting this
Yields this:
---
> [inspect] Add support for printing compact qualified keywords
